src/Entity/Tuto.php
<?php

namespace App\Entity;

use App\Repository\TutoRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
// use Symfony\Component\HttpFoundation\File\File;
// use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: TutoRepository::class)]
class Tuto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 120)]
    private ?string $Title = null;

    #[ORM\Column(type: Types::ARRAY)]
    private array $Categories = [];

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    private $imageFile;


    // #[ORM\Column(type: "datetime_immutable", nullable: true)]
    // private ?\DateTimeImmutable $updatedAt = null;


    #[ORM\ManyToMany(targetEntity: User::class, mappedBy: 'Tuto')]
    private Collection $users;

    #[ORM\Column(type: "datetime_immutable", nullable: true)]
    private ?\DateTimeImmutable $updatedAt = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $file = null;

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeImmutable $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }


    public function __construct()
    {
        $this->users = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getCategories(): array
    {
        return $this->Categories;
    }

    public function setCategories(array $Categories): self
    {
        $this->Categories = $Categories;

        return $this;
    }

    public function getImageFile()
    { 
        return $this->imageFile;
    }

    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;
    } 


    public function getImage(): ?string
    {
        dump('get');
        return $this->image;
    }

    public function setImage(string $image): self
    {
        dump('set');
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getUsers(): Collection
    {
        return $this->users;
    }

    public function addUser(User $user): self
    {
        if (!$this->users->contains($user)) {
            $this->users->add($user);
            $user->addTuto($this);
        }

        return $this;
    }

    public function removeUser(User $user): self
    {
        if ($this->users->removeElement($user)) {
            $user->removeTuto($this);
        }

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getFile(): ?string
    {
        return $this->file;
    }

    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Tuto;
use Doctrine\ORM\EntityManagerInterface;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $repository = $entityManager->getRepository(Tuto::class);
        $tutos = $repository->findAll();
        $userIsConnected = $this->getUser() !== null;

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'tutos' => $tutos,
            'userIsConnected' => $userIsConnected,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/main.css') }}">
    {{ encore_entry_link_tags('app') }}
{% endblock %}

{% block title %}Home{% endblock %}

{% block body %}
<section class="margin-lr">

<div class="introduction-section">
    <h1 class="introduction-h1">Bienvenue sur RubyTips !</h1>
    <h2 class="introduction-h2">Développez votre expertise en Ruby, débutant comme codeur confirmé !</h2>
    <img src="{{ asset('uploads/17950-1024x814.png') }}" class="introduction-image" alt="Description de l'image">
</div>
    <div class="content-container">
        <div class="card">
            <h3 class="introduction-h3">📚 <strong>Qu'est-ce que RubyTips ?</strong></h3>
            <p class="introduction-p">C'est une plateforme dédiée à la maîtrise du langage de programmation Ruby. Ici, vous trouverez des tutoriels vidéo et des articles détaillés.</p>
        </div>
        <div class="card">
            <h3 class="introduction-h3">💡 <strong>Pourquoi choisir RubyTips ?</strong></h3>
            <p class="introduction-p">Il existe de nombreuses ressources en ligne pour apprendre Ruby, mais RubyTips se démarque par la qualité de son contenu.</p>
        </div>
        <div class="card">
            <h3 class="introduction-h3">👥 <strong>Rejoignez une communauté dynamique !</strong></h3>
            <p class="introduction-p">Ne partez pas à l'aventure seul ! RubyTips est aussi une communauté de passionnés de Ruby.</p>
        </div>
        <div class="card">
            <h3 class="introduction-h3">📣 <strong>Prêt à plonger dans le monde fascinant de Ruby ?</strong></h3>
            <p class="introduction-p">Créez un compte gratuitement dès aujourd'hui pour accéder à des contenus exclusifs et commencer votre apprentissage.</p>
        </div>
    </div>
    <a href="#" class="cta-button introduction-btn">👇 Naviguez en dessous et trouvez les tutos fait pour vous !</a>



<h2 class="category-title">Découvrez nos meilleurs tutoriels en vidéo !</h2>
<p class="category-subtitle">Tous les tutoriels en vidéo pour apprendre les bases de ruby sont ici.</p>
<div class="linegradient linevideo"></div>
<div class="row">
    {% for tuto in tutos %}
        {% if 'video' in tuto.categories %}
            <div class="col-md-4">
                <div class="tuto-card">
                    <img src="{{ asset('uploads/' ~ tuto.image) }}" class="tuto-image" />
                    <h2 class="tuto-title"><a href="{{ path('app_tuto_show', {'id': tuto.id}) }}" class="tuto-link">{{ tuto.title }}</a></h2>
                    <p class="tuto-category">Tuto Vidéo</p>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>

<h2 class="category-title">Nos tutos écrits sont les plus complets !</h2>
<p class="category-subtitle">Vous préférez la lecture et prendre votre temps étape par étape, nos tutos rédigés sont pour vous.</p>
<div class="linegradient linedocs"></div>
<div class="row">
    {% for tuto in tutos %}
        {% if 'docs' in tuto.categories %}
            <div class="col-md-4">
                <div class="tuto-card">
                    <img src="{{ asset('uploads/' ~ tuto.image) }}" class="tuto-image" />
                    <h2 class="tuto-title"><a href="{{ path('app_tuto_show', {'id': tuto.id}) }}" class="tuto-link">{{ tuto.title }}</a></h2>
                    <p class="tuto-category">Tuto Écrit</p>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>

<h2 class="category-title">Toujours plus de tutoriels !</h2>
<p class="category-subtitle">Les autres tutoriels sont dans cette catégorie, pour en apprendre toujours plus.</p>
<div class="linegradient linemotion"></div>
<div class="row">
    {% for tuto in tutos %}
        {% if 'motion' in tuto.categories %}
            <div class="col-md-4">
                <div class="tuto-card">
                    <img src="{{ asset('uploads/' ~ tuto.image) }}" class="tuto-image" />
                    <h2 class="tuto-title"><a href="{{ path('app_tuto_show', {'id': tuto.id}) }}" class="tuto-link">{{ tuto.title }}</a></h2>
                    <p class="tuto-category">Tuto Motion</p>
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
</section>

{% endblock %}

{% block javascripts %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const userIsConnected = {{ userIsConnected ? 'true' : 'false' }};
        // Récupérer tous les liens de tutoriel
        const tutoLinks = document.querySelectorAll('.tuto-link');

        // Ajouter un écouteur d'événements à chaque lien
        tutoLinks.forEach(link => {
            link.addEventListener('click', function(event) {
                if (!userIsConnected) {
                    event.preventDefault(); // Empêcher la navigation vers le lien
                    alert('Veuillez vous connecter pour consulter ce tutoriel.'); // Afficher le pop-up
                }
            });
        });
    });
</script>
{% endblock %}